version: '3.1'

networks:
  app-tier:
    driver: bridge

services:

  postgres:
    container_name: postgres
    image: bitnami/postgresql:14
    restart: always
    env_file: db_cred.env
    volumes:
      - ./dbinit.sh:/docker-entrypoint-initdb.d/dbinit.sh
      - dbdata:/bitnami/postgresql
    networks:
      - app-tier

  bgpkit-broker-api:
    container_name: bgpkit-broker-api
    entrypoint: bash -c 'while !</dev/tcp/postgres/5432; do sleep 30; echo "wait for postgres"; done; service cron start; /usr/local/bin/start_api'
    ports:
      - "18888:18888"
    build:
      dockerfile: deployment/Dockerfile
      context: ..
    restart: always
    env_file: db_cred.env
    depends_on:
      - postgres
    networks:
      - app-tier

volumes:
  dbdata:
