version: '3.8'

networks:
  app-tier:
    driver: bridge

services:

  bgpkit-broker-postgres:
    container_name: bgpkit-broker-postgres
    build:
      dockerfile: deployment/Dockerfile.postgres
      context: ..
    restart: always
    env_file: db_cred.env
    volumes:
      - ./dbinit.sh:/docker-entrypoint-initdb.d/dbinit.sh
      - dbdata:/bitnami/postgresql
    networks:
      - app-tier

  updater:
    container_name: bgpkit-broker-updater
    entrypoint: bash -c 'sleep 10; while !</dev/tcp/bgpkit-broker-postgres/5432; do sleep 60; echo "wait for postgres"; done; supercronic /etc/cron.d/updater-crontab'
    build:
      dockerfile: deployment/Dockerfile.updater
      context: ..
    restart: always
    env_file: db_cred.env
    depends_on:
      - bgpkit-broker-postgres
    networks:
      - app-tier

  api:
    container_name: bgpkit-broker-api
    entrypoint: bash -c 'sleep 10; while !</dev/tcp/bgpkit-broker-postgres/5432; do sleep 60; echo "wait for postgres"; done; /usr/local/bin/start_api'
    ports:
      - "18888:18888"
    build:
      dockerfile: deployment/Dockerfile.api
      context: ..
    restart: always
    env_file: db_cred.env
    depends_on:
      - bgpkit-broker-postgres
    networks:
      - app-tier

volumes:
  dbdata:
