version: '3.1'

networks:
  app-tier:
    driver: bridge

services:

  postgres:
    container_name: postgres
    image: bitnami/postgresql:14
    restart: always
    environment:
      POSTGRES_PASSWORD: broker
      POSTGRES_USER: broker_user
      POSTGRES_DB: broker
    volumes:
      - ./dbinit.sh:/docker-entrypoint-initdb.d/dbinit.sh
      - dbdata:/bitnami/postgresql
    networks:
      - app-tier

  bgpkit-broker-api:
    container_name: bgpkit-broker-api
    entrypoint: bash -c 'while !</dev/tcp/postgres/5432; do sleep 60; echo "wait for postgres"; done; service cron start; /usr/local/bin/bgpkit-broker-api'
    ports:
      - "8080:8080"
    build:
      dockerfile: deployment/Dockerfile
      context: ..
    restart: always
    environment:
      DATABASE_URL: postgres://broker_user:broker@postgres/broker
    depends_on:
      - postgres
    networks:
      - app-tier

volumes:
  dbdata: